---
- name: Update hostname
  hosts: all
  become: yes
  tasks:
    - name: Set hostname
      lineinfile:
        path: /etc/hostname
        regexp: '^.*$'
        line: 'oleksandr-kozak-lab2'
      notify: restart hostname
  handlers:
    - name: restart hostname
      command: hostnamectl set-hostname oleksandr-kozak-lab2
